# Postgres

development:
  adapter: postgresql
  encoding: unicode
  database: socialnetwork_dev
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: socialnetwork_test
  pool: 5
  username: postgres
  password: password

production:
  url: <%= ENV['DATABASE_URL'] %>
